/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utama;

import admin.Admin;
import java.awt.Container;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import laporan.Laporan;
import pajak.Pajak;
import pengujian.Pengujian;
import perizinan.Perizinan;
import perpanjangan.Perpanjangan;
import sertifikasi.Sertifikasi;
import smsperingatan.Smsperingatan;
import sppbe.Global;
import user.User;

/**
 *
 * @author Gerardo
 */
public class Utama extends javax.swing.JFrame {

    Global global;

    /**
     * Creates new form utama
     */
    public Utama() {
        initComponents();
        global = new Global();

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowListener() {

            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println("closing...");
                // Tutup semua midi form
                JInternalFrame[] children = jDesktopPane1.getAllFrames();
                for (JInternalFrame f : children) {
                    f.dispose();
                }
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    private boolean formHasCreated(Object object) {
        JInternalFrame[] children = jDesktopPane1.getAllFrames();
        for (JInternalFrame form : children) {
            if (form.getClass().getCanonicalName().equals(object.getClass().getCanonicalName())) {
                try {
                    form.setSelected(true);
                } catch (PropertyVetoException ex) {
                }
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("S P P B E");

        jLabel2.setText("PT. PUTRA SINDO");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(":: Selamat Datang ::");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("MENU UTAMA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addComponent(jLabel3)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jMenu1.setText("User     ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pajak.png"))); // NOI18N
        jMenu11.setText("Pajak     ");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu11);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/perizinan.png"))); // NOI18N
        jMenu12.setText("Perizinan     ");
        jMenu12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu12);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pengujian.png"))); // NOI18N
        jMenu4.setText("Pengujian     ");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sertifikasi16.png"))); // NOI18N
        jMenu5.setText("Sertifikasi     ");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/perpanjangan.png"))); // NOI18N
        jMenu6.setText("Perpanjangan     ");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sms.png"))); // NOI18N
        jMenu7.setText("SMS Peringatan     ");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/laporan.png"))); // NOI18N
        jMenu8.setText("Laporan     ");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        jMenu9.setText("Admin     ");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jMenu10.setText("Logout");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked

        Admin admin1 = new Admin();
        if (!formHasCreated(admin1)) {
            jDesktopPane1.add(admin1);
            admin1.show();
        }

        BasicInternalFrameUI x = (BasicInternalFrameUI) admin1.getUI();
        Container north = (Container) x.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();

        try {
            admin1.setMaximum(true);
        } catch (PropertyVetoException e) {
            //maximize otomatis
        }
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        User user1 = new User();
        if (!formHasCreated(user1)) {
            jDesktopPane1.add(user1);
            user1.show();
        }

        BasicInternalFrameUI x = (BasicInternalFrameUI) user1.getUI();
        Container north = (Container) x.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();

        try {
            user1.setMaximum(true);
        } catch (PropertyVetoException e) {
            //maximize otomatis
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked

        Pajak pajak1 = new Pajak();
        if (!formHasCreated(pajak1)) {
            jDesktopPane1.add(pajak1);
            pajak1.show();
        }

        BasicInternalFrameUI x = (BasicInternalFrameUI) pajak1.getUI();
        Container north = (Container) x.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();

        try {
            pajak1.setMaximum(true);
        } catch (PropertyVetoException e) {
            //maximize otomatis
        }
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked

        Perizinan perizinan1 = new Perizinan();
        if (!formHasCreated(perizinan1)) {
            jDesktopPane1.add(perizinan1);
            perizinan1.show();
        }

        BasicInternalFrameUI x = (BasicInternalFrameUI) perizinan1.getUI();
        Container north = (Container) x.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();

        try {
            perizinan1.setMaximum(true);
        } catch (PropertyVetoException e) {
            //maximize otomatis
        }
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked

        Pengujian pengujian1 = new Pengujian();
        if (!formHasCreated(pengujian1)) {
            jDesktopPane1.add(pengujian1);
            pengujian1.show();
        }

        BasicInternalFrameUI x = (BasicInternalFrameUI) pengujian1.getUI();
        Container north = (Container) x.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();

        try {
            pengujian1.setMaximum(true);
        } catch (PropertyVetoException e) {
            //maximize otomatis
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked

        Sertifikasi sertifikasi1 = new Sertifikasi();
        if (!formHasCreated(sertifikasi1)) {
            jDesktopPane1.add(sertifikasi1);
            sertifikasi1.show();
        }

        BasicInternalFrameUI x = (BasicInternalFrameUI) sertifikasi1.getUI();
        Container north = (Container) x.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();

        try {
            sertifikasi1.setMaximum(true);
        } catch (PropertyVetoException e) {
            //maximize otomatis
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked

        Perpanjangan perpanjangan1 = new Perpanjangan();
        if (!formHasCreated(perpanjangan1)) {
            jDesktopPane1.add(perpanjangan1);
            perpanjangan1.show();
        }

        BasicInternalFrameUI x = (BasicInternalFrameUI) perpanjangan1.getUI();
        Container north = (Container) x.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();

        try {
            perpanjangan1.setMaximum(true);
        } catch (PropertyVetoException e) {
            //maximize otomatis
        }
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked

        Smsperingatan smsperingatan1 = new Smsperingatan();
        if (!formHasCreated(smsperingatan1)) {
            jDesktopPane1.add(smsperingatan1);
            smsperingatan1.show();
        }

        BasicInternalFrameUI x = (BasicInternalFrameUI) smsperingatan1.getUI();
        Container north = (Container) x.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();

        try {
            smsperingatan1.setMaximum(true);
        } catch (PropertyVetoException e) {
            //maximize otomatis
        }
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked

        Laporan laporan = new Laporan();
        if (!formHasCreated(laporan)) {
            jDesktopPane1.add(laporan);
            laporan.show();
        }

        BasicInternalFrameUI x = (BasicInternalFrameUI) laporan.getUI();
        Container north = (Container) x.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();

        try {
            laporan.setMaximum(true);
        } catch (PropertyVetoException e) {
            //maximize otomatis
        }
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        global.konfirmasiKeluar(rootPane);
    }//GEN-LAST:event_jMenu10MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
